import { describe, expect } from 'vitest'
import { test } from './pg-test'
import type { TestClient } from 'feather-testing-postgres'

// IMP-005: POST /api/table/:table:import — the bulk-import collection action.
// Every row goes through the full saveDoc lifecycle in insert mode.

const DT = 'Import Target'
const PATH = `/api/table/${encodeURIComponent(DT)}:import`

async function setup(admin: TestClient, extra: Record<string, unknown> = {}) {
  await admin.post('/api/doctype', {
    name: DT,
    columns: [
      { column_name: 'title', column_type: 'Data', reqd: true },
      { column_name: 'qty', column_type: 'Int' },
      { column_name: 'stage', column_type: 'Choice', choices: 'New\nDone' },
      { column_name: 'active', column_type: 'Check' },
      { column_name: 'due', column_type: 'Date' },
    ],
    ...extra,
  })
}

describe('IMP-005: bulk import', () => {
  test('inserts rows through the full lifecycle', async ({ admin }) => {
    await setup(admin)
    const res = await admin.post<{ inserted: number; failed: unknown[] }>(PATH, {
      rows: [
        { title: 'first', qty: '2', stage: 'New', active: true, due: '2026-01-15' },
        { title: 'second', qty: 5 },
        { title: 'third' },
      ],
    })
    expect(res).toEqual({ inserted: 3, failed: [] })

    const list = await admin.get<{ data: Record<string, unknown>[] }>(
      `/api/table/${encodeURIComponent(DT)}?fields=${encodeURIComponent(
        '["name","title","qty","active","due","created_by"]',
      )}&order_by=${encodeURIComponent('title asc')}`,
    )
    expect(list.data).toHaveLength(3)
    const first = list.data[0]
    expect(first.title).toBe('first')
    expect(Number(first.qty)).toBe(2) // "2" coerced into the bigint column (serialized back as a string)
    expect(first.active).toBe(true)
    expect(String(first.due)).toContain('2026-01-15')
    expect(first.created_by).toBe('Administrator')
    expect(first.name).toBeTruthy() // id generated by the naming engine
  })

  test('reports bad rows by index while good rows still land', async ({ admin }) => {
    await setup(admin)
    const res = await admin.post<{
      inserted: number
      failed: { index: number; message: string; fields?: Record<string, string> }[]
    }>(PATH, {
      rows: [
        { title: 'good one' },
        { qty: 9 }, // missing reqd title
        { title: 'bad choice', stage: 'Nope' },
        { title: 'good two' },
      ],
    })
    expect(res.inserted).toBe(2)
    expect(res.failed.map((f) => f.index)).toEqual([1, 2])
    expect(res.failed[0].fields).toHaveProperty('title')
    expect(res.failed[1].fields).toHaveProperty('stage')

    const count = await admin.get<{ count: number }>(
      `/api/table/${encodeURIComponent(DT)}:count`,
    )
    expect(count.count).toBe(2)
  })

  test('insert mode: a duplicate explicit name conflicts instead of updating', async ({
    admin,
  }) => {
    await setup(admin, { id_pattern: 'prompt' })
    const res = await admin.post<{
      inserted: number
      failed: { index: number; message: string }[]
    }>(PATH, {
      rows: [
        { name: 'ROW-1', title: 'original' },
        { name: 'ROW-1', title: 'sneaky update' },
      ],
    })
    expect(res.inserted).toBe(1)
    expect(res.failed).toHaveLength(1)
    expect(res.failed[0].index).toBe(1)

    const doc = await admin.get<{ title: string }>(
      `/api/table/${encodeURIComponent(DT)}/ROW-1`,
    )
    expect(doc.title).toBe('original')
  })

  test('requires create permission — whole request 403s, nothing inserted', async ({
    admin,
    createUser,
  }) => {
    await setup(admin)
    const user = await createUser({})
    const res = await user.fetch(PATH, {
      method: 'POST',
      body: JSON.stringify({ rows: [{ title: 'nope' }] }),
    })
    expect(res.status).toBe(403)
    const count = await admin.get<{ count: number }>(
      `/api/table/${encodeURIComponent(DT)}:count`,
    )
    expect(count.count).toBe(0)
  })

  test('validates its arguments', async ({ admin }) => {
    await setup(admin)
    for (const body of [{}, { rows: [] }, { rows: 'nope' }]) {
      const res = await admin.fetch(PATH, { method: 'POST', body: JSON.stringify(body) })
      expect(res.status).toBe(417)
    }
    const over = await admin.fetch(PATH, {
      method: 'POST',
      body: JSON.stringify({ rows: Array.from({ length: 10_001 }, () => ({ title: 'x' })) }),
    })
    expect(over.status).toBe(417)
    expect(((await over.json()) as { error: { message: string } }).error.message).toContain(
      'capped',
    )
  })

  test('non-object rows are reported, not crashed on', async ({ admin }) => {
    await setup(admin)
    const res = await admin.post<{ inserted: number; failed: { index: number }[] }>(PATH, {
      rows: [{ title: 'ok' }, 'just a string', [1, 2], null],
    })
    expect(res.inserted).toBe(1)
    expect(res.failed.map((f) => f.index)).toEqual([1, 2, 3])
  })

  test('refuses settings and sub_table kinds', async ({ admin }) => {
    await admin.post('/api/doctype', {
      name: 'Import Settings',
      kind: 'settings',
      columns: [{ column_name: 'title', column_type: 'Data' }],
    })
    const s = await admin.fetch(`/api/table/${encodeURIComponent('Import Settings')}:import`, {
      method: 'POST',
      body: JSON.stringify({ rows: [{ title: 'x' }] }),
    })
    expect(s.status).toBe(417)

    await admin.post('/api/doctype', {
      name: 'Import Child',
      kind: 'sub_table',
      columns: [{ column_name: 'title', column_type: 'Data' }],
    })
    const c = await admin.fetch(`/api/table/${encodeURIComponent('Import Child')}:import`, {
      method: 'POST',
      body: JSON.stringify({ rows: [{ title: 'x' }] }),
    })
    expect(c.status).toBe(417)
  })

  test('is write-effect: GET :import is refused, and discovery lists it', async ({ admin }) => {
    await setup(admin)
    const get = await admin.fetch(PATH)
    expect(get.status).toBe(404)

    const actions = await admin.get<{
      collection: { action: string; effect: string }[]
    }>(`/api/table/${encodeURIComponent(DT)}:actions`)
    expect(actions.collection).toContainEqual(
      expect.objectContaining({ action: 'import', effect: 'write' }),
    )
  })
})
