import { test } from './fixtures'

// This is a deliberate deep link: the contract under test is the builder's
// semantic control interface, while table-builder.spec.ts proves navigation.
test('#294: table builder controls expose their purpose and column context', async ({ session }) => {
  await session
    .visit('/admin/new-table')
    .assertHas('[data-testid="table-builder"]')
    .fillIn('Table name', 'Accessible inventory')
    .fillIn('Module', 'Custom')
    .clickButton('+ Add column')
    .fillIn('Column 1 field label', 'Item')
    .fillIn('Column 1 database name', 'item')
    .selectOption('Column 1 type', 'Choice')
    .fillIn('Column 1 details', 'Small, Medium')
    .check('Column 1 required')
    .check('Column 1 show in list')
    .fillIn('Column 2 field label', 'Warehouse')
    .fillIn('Column 2 database name', 'warehouse')
    .selectOption('Column 2 type', 'Data')
    .check('Column 2 show in list')
    .clickButton('Remove column 2')
    .assertHas('[data-columnrow]', { count: 1 })
    .clickButton('+ Add column')
    .selectOption('Row naming method', 'Series with prefix')
    .fillIn('Series prefix', 'INV-')
    .selectOption('Series digits', '0001, 0002…')
    .clickButton('Cards')
    .fillIn('Column 1 field label', 'Card item')
    .clickButton('Column 1 type Pick from a list')
    .fillIn('Column 1 choices', 'Single, Case')
    .uncheck('Column 1 required')
    .fillIn('Column 2 field label', 'Card warehouse')
    .clickButton('Column 2 type Link to another table')
    .selectOption('Column 2 linked table', 'Choose a table…')
    .check('Column 2 required')
    .clickButton('Remove column 2')
    .assertHas('[data-testid^="dt-card-"][role="group"]', { count: 1 })
})
