import { describe, expect } from 'vitest'
import { test } from '../pg-test'
import type { TestClient } from 'feather-testing-postgres'

// IMP-005: POST /api/table/:table:import — the bulk-import collection action.
// Every row goes through the full saveDoc lifecycle in insert mode.

const DT = 'Import Target'
const PATH = `/api/table/${encodeURIComponent(DT)}:import`

async function setup(admin: TestClient, extra: Record<string, unknown> = {}) {
  await admin.post('/api/table_def', {
    name: DT,
    columns: [
      { column_name: 'title', column_type: 'Data', reqd: true },
      { column_name: 'qty', column_type: 'Int' },
      { column_name: 'stage', column_type: 'Choice', choices: 'New\nDone' },
      { column_name: 'active', column_type: 'Check' },
      { column_name: 'due', column_type: 'Date' },
    ],
    ...extra,
  })
}

describe('IMP-005: bulk import', () => {
  test('inserts rows through the full lifecycle', async ({ admin }) => {
    await setup(admin)
    const res = await admin.post<{ inserted: number; failed: unknown[] }>(PATH, {
      rows: [
        { title: 'first', qty: '2', stage: 'New', active: true, due: '2026-01-15' },
        { title: 'second', qty: 5 },
        { title: 'third' },
      ],
    })
    expect(res).toEqual({ inserted: 3, failed: [] })

    const list = await admin.get<{ data: Record<string, unknown>[] }>(
      `/api/table/${encodeURIComponent(DT)}?fields=${encodeURIComponent(
        '["row_id","title","qty","active","due","created_by"]',
      )}&order_by=${encodeURIComponent('title asc')}`,
    )
    expect(list.data).toHaveLength(3)
    const first = list.data[0]
    expect(first.title).toBe('first')
    expect(Number(first.qty)).toBe(2) // "2" coerced into the bigint column (serialized back as a string)
    expect(first.active).toBe(true)
    expect(String(first.due)).toContain('2026-01-15')
    expect(first.created_by).toBe('Administrator')
    expect(first.row_id).toMatch(/^[0-9a-f]{10}$/) // id generated by the naming engine
  })

  test('reports bad rows by index while good rows still land', async ({ admin }) => {
    await setup(admin)
    const res = await admin.post<{
      inserted: number
      failed: { index: number; message: string; fields?: Record<string, string> }[]
    }>(PATH, {
      rows: [
        { title: 'good one' },
        { qty: 9 }, // missing reqd title
        { title: 'bad choice', stage: 'Nope' },
        { title: 'good two' },
      ],
    })
    expect(res.inserted).toBe(2)
    expect(res.failed.map((f) => f.index)).toEqual([1, 2])
    expect(res.failed[0].fields).toHaveProperty('title')
    expect(res.failed[1].fields).toHaveProperty('stage')

    const count = await admin.get<{ count: number }>(
      `/api/table/${encodeURIComponent(DT)}:count`,
    )
    expect(count.count).toBe(2)
  })

  test('insert mode: a duplicate explicit name conflicts instead of updating', async ({
    admin,
  }) => {
    await setup(admin, { id_pattern: 'prompt' })
    const res = await admin.post<{
      inserted: number
      failed: { index: number; message: string }[]
    }>(PATH, {
      rows: [
        { row_id: 'ROW-1', title: 'original' },
        { row_id: 'ROW-1', title: 'sneaky update' },
      ],
    })
    expect(res.inserted).toBe(1)
    expect(res.failed).toHaveLength(1)
    expect(res.failed[0].index).toBe(1)

    const doc = await admin.get<{ title: string }>(
      `/api/table/${encodeURIComponent(DT)}/ROW-1`,
    )
    expect(doc.title).toBe('original')
  })

  test('requires create permission — whole request 403s, nothing inserted', async ({
    admin,
    createUser,
  }) => {
    await setup(admin)
    const user = await createUser({})
    const res = await user.fetch(PATH, {
      method: 'POST',
      body: JSON.stringify({ rows: [{ title: 'nope' }] }),
    })
    expect(res.status).toBe(403)
    const count = await admin.get<{ count: number }>(
      `/api/table/${encodeURIComponent(DT)}:count`,
    )
    expect(count.count).toBe(0)
  })

  test('validates its arguments', async ({ admin }) => {
    await setup(admin)
    for (const body of [{}, { rows: [] }, { rows: 'nope' }]) {
      const res = await admin.fetch(PATH, { method: 'POST', body: JSON.stringify(body) })
      expect(res.status).toBe(417)
    }
    const over = await admin.fetch(PATH, {
      method: 'POST',
      body: JSON.stringify({ rows: Array.from({ length: 10_001 }, () => ({ title: 'x' })) }),
    })
    expect(over.status).toBe(417)
    expect(((await over.json()) as { error: { message: string } }).error.message).toContain(
      'capped',
    )
  })

  test('non-object rows are reported, not crashed on', async ({ admin }) => {
    await setup(admin)
    const res = await admin.post<{ inserted: number; failed: { index: number }[] }>(PATH, {
      rows: [{ title: 'ok' }, 'just a string', [1, 2], null],
    })
    expect(res.inserted).toBe(1)
    expect(res.failed.map((f) => f.index)).toEqual([1, 2, 3])
  })

  test('refuses settings and sub_table kinds', async ({ admin }) => {
    await admin.post('/api/table_def', {
      name: 'Import Settings',
      kind: 'settings',
      columns: [{ column_name: 'title', column_type: 'Data' }],
    })
    const s = await admin.fetch(`/api/table/${encodeURIComponent('Import Settings')}:import`, {
      method: 'POST',
      body: JSON.stringify({ rows: [{ title: 'x' }] }),
    })
    expect(s.status).toBe(417)

    await admin.post('/api/table_def', {
      name: 'Import Child',
      kind: 'sub_table',
      columns: [{ column_name: 'title', column_type: 'Data' }],
    })
    const c = await admin.fetch(`/api/table/${encodeURIComponent('Import Child')}:import`, {
      method: 'POST',
      body: JSON.stringify({ rows: [{ title: 'x' }] }),
    })
    expect(c.status).toBe(417)
  })

  test('dry_run validates every row and writes nothing', async ({ admin }) => {
    await setup(admin)
    const res = await admin.post<{
      dry_run: boolean
      valid: number
      failed: { index: number; message: string; fields?: Record<string, string> }[]
    }>(PATH, {
      dry_run: true,
      rows: [
        { title: 'fine', qty: '3', stage: 'New' },
        { qty: 1 }, // missing reqd title
        { title: 'bad', stage: 'Nope' }, // invalid choice
      ],
    })
    expect(res.dry_run).toBe(true)
    expect(res.valid).toBe(1)
    expect(res.failed.map((f) => f.index)).toEqual([1, 2])
    expect(res.failed[0].fields).toHaveProperty('title')

    const count = await admin.get<{ count: number }>(
      `/api/table/${encodeURIComponent(DT)}:count`,
    )
    expect(count.count).toBe(0) // nothing written
  })

  test('dry_run flags existing-name conflicts and duplicates within the file', async ({
    admin,
  }) => {
    await setup(admin, { id_pattern: 'prompt' })
    await admin.post(PATH, { rows: [{ row_id: 'ROW-1', title: 'already here' }] })
    const res = await admin.post<{
      valid: number
      failed: { index: number; message: string }[]
    }>(PATH, {
      dry_run: true,
      rows: [
        { row_id: 'ROW-1', title: 'conflicts with DB' },
        { row_id: 'ROW-2', title: 'ok' },
        { row_id: 'ROW-2', title: 'duplicate within file' },
        { title: 'prompt table needs a name' },
      ],
    })
    expect(res.valid).toBe(1)
    expect(res.failed.map((f) => f.index)).toEqual([0, 2, 3])
  })

  test('dry_run still requires create permission', async ({ admin, createUser }) => {
    await setup(admin)
    const user = await createUser({})
    const res = await user.fetch(PATH, {
      method: 'POST',
      body: JSON.stringify({ dry_run: true, rows: [{ title: 'x' }] }),
    })
    expect(res.status).toBe(403)
  })

  test('every import writes an Import Log row; dry runs write none', async ({ admin }) => {
    await setup(admin)
    await admin.post(PATH, { dry_run: true, rows: [{ title: 'checked only' }] })
    await admin.post(PATH, {
      rows: [{ title: 'ok' }, { qty: 1 }],
      context: {
        file_name: 'q3.xlsx',
        sheet_name: 'Zone',
        table_created: true,
        part: 1,
        parts: 1,
      },
    })
    const logs = await admin.get<{ data: Record<string, unknown>[] }>(
      `/api/table/${encodeURIComponent('Import Log')}?fields=${encodeURIComponent(
        '["ref_table","file_name","sheet_name","table_created","inserted","failed","error_summary","part","parts"]',
      )}&filters=${encodeURIComponent(JSON.stringify([['ref_table', '=', DT]]))}`,
    )
    expect(logs.data).toHaveLength(1) // the dry run logged nothing
    const log = logs.data[0]
    expect(log).toMatchObject({
      ref_table: DT,
      file_name: 'q3.xlsx',
      sheet_name: 'Zone',
      table_created: true,
    })
    expect(Number(log.inserted)).toBe(1)
    expect(Number(log.failed)).toBe(1)
    expect(String(log.error_summary)).toContain('#1')
    expect(Number(log.part)).toBe(1)
  })

  test('an import without context still logs bare counts', async ({ admin }) => {
    await setup(admin)
    await admin.post(PATH, { rows: [{ title: 'a' }, { title: 'b' }] })
    const logs = await admin.get<{ data: Record<string, unknown>[] }>(
      `/api/table/${encodeURIComponent('Import Log')}?filters=${encodeURIComponent(
        JSON.stringify([['ref_table', '=', DT]]),
      )}&fields=${encodeURIComponent('["inserted","file_name"]')}`,
    )
    expect(logs.data).toHaveLength(1)
    expect(Number(logs.data[0].inserted)).toBe(2)
    expect(logs.data[0].file_name).toBeNull()
  })

  test('is write-effect: GET :import is refused, and discovery lists it', async ({ admin }) => {
    await setup(admin)
    const get = await admin.fetch(PATH)
    expect(get.status).toBe(404)

    const actions = await admin.get<{
      collection: { action: string; effect: string }[]
    }>(`/api/table/${encodeURIComponent(DT)}:actions`)
    expect(actions.collection).toContainEqual(
      expect.objectContaining({ action: 'import', effect: 'write' }),
    )
  })
})
