// Generated by scripts/codegen-doctypes.ts — do not edit.
// Deterministic output of (doctypes/*.json + doctypes/materializations.json).
import { defineTable } from "convex/server";
import { v } from "convex/values";
import type { DocTypeDefinition } from "./doctype/definition";

export const doctypeTables = {
  dt_customer: defineTable(v.any())
    .index("by_email", ["email"])
    .index("by_company", { fields: ["company"], staged: true }),
  dt_invoice: defineTable({
    owner: v.string(),
    creation: v.number(),
    modified: v.number(),
    docstatus: v.number(),
    customer: v.string(),
    amount: v.number(),
    status: v.optional(v.union(v.literal("draft"), v.literal("paid"))),
    archived: v.optional(v.boolean()),
    notes: v.optional(v.string()),
  })
    .index("by_customer", ["customer"])
    .index("by_amount", ["amount"])
    .index("by_status", ["status"])
    .index("by_archived", ["archived"]),
};

export const nativeIndexes: Record<string, readonly string[]> = {
  customer: ["email"],
  invoice: ["customer", "amount", "status", "archived"],
};

export const packageDefinitions: DocTypeDefinition[] = [
  {
    "name": "invoice",
    "label": "Invoice",
    "fields": [
      {
        "name": "customer",
        "label": "Customer",
        "type": "text",
        "required": true,
        "filterable": true
      },
      {
        "name": "amount",
        "type": "number",
        "required": true,
        "filterable": true
      },
      {
        "name": "status",
        "type": "select",
        "filterable": true,
        "options": [
          "draft",
          "paid"
        ]
      },
      {
        "name": "archived",
        "type": "boolean",
        "filterable": true
      },
      {
        "name": "notes",
        "type": "text"
      }
    ]
  }
];

export type Invoice = {
  customer: string;
  amount: number;
  status?: "draft" | "paid";
  archived?: boolean;
  notes?: string;
};
